//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaunchDarkly.AuthReader {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mytravel.se", ConfigurationName="AuthReader.AuthReaderSoap")]
    public interface AuthReaderSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/GetActiveDirectoryUserInformation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LaunchDarkly.AuthReader.ActiveDirectoryUserInformationResponse GetActiveDirectoryUserInformation(string userId, string callerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/GetActiveDirectoryUserInformation", ReplyAction="*")]
        System.Threading.Tasks.Task<LaunchDarkly.AuthReader.ActiveDirectoryUserInformationResponse> GetActiveDirectoryUserInformationAsync(string userId, string callerId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mytravel.se")]
    public partial class ActiveDirectoryUserInformationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Message[] messagesField;
        
        private ActiveDirectoryUserInformation userField;
        
        private int databaseIdField;
        
        private string databaseNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Message[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
                this.RaisePropertyChanged("Messages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ActiveDirectoryUserInformation User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int DatabaseId {
            get {
                return this.databaseIdField;
            }
            set {
                this.databaseIdField = value;
                this.RaisePropertyChanged("DatabaseId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DatabaseName {
            get {
                return this.databaseNameField;
            }
            set {
                this.databaseNameField = value;
                this.RaisePropertyChanged("DatabaseName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mytravel.se")]
    public partial class Message : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string logMsgField;
        
        private string userMsgField;
        
        private string classNameField;
        
        private string propertyNameField;
        
        private string requestIdField;
        
        private string serviceIdField;
        
        private int messageIdField;
        
        private int severityIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string logMsg {
            get {
                return this.logMsgField;
            }
            set {
                this.logMsgField = value;
                this.RaisePropertyChanged("logMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string userMsg {
            get {
                return this.userMsgField;
            }
            set {
                this.userMsgField = value;
                this.RaisePropertyChanged("userMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string className {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
                this.RaisePropertyChanged("className");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string propertyName {
            get {
                return this.propertyNameField;
            }
            set {
                this.propertyNameField = value;
                this.RaisePropertyChanged("propertyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("requestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string serviceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
                this.RaisePropertyChanged("serviceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("messageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int severityId {
            get {
                return this.severityIdField;
            }
            set {
                this.severityIdField = value;
                this.RaisePropertyChanged("severityId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mytravel.se")]
    public partial class ActiveDirectoryUserInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNumberField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string titleField;
        
        private string phoneNumberField;
        
        private string faxNumberField;
        
        private string cellPhoneNumberField;
        
        private string emailField;
        
        private string addressField;
        
        private string cityField;
        
        private string zipCodeField;
        
        private string countryField;
        
        private string departmentField;
        
        private string managerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserNumber {
            get {
                return this.userNumberField;
            }
            set {
                this.userNumberField = value;
                this.RaisePropertyChanged("UserNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("PhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FaxNumber {
            get {
                return this.faxNumberField;
            }
            set {
                this.faxNumberField = value;
                this.RaisePropertyChanged("FaxNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CellPhoneNumber {
            get {
                return this.cellPhoneNumberField;
            }
            set {
                this.cellPhoneNumberField = value;
                this.RaisePropertyChanged("CellPhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("ZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
                this.RaisePropertyChanged("Department");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ManagerId {
            get {
                return this.managerIdField;
            }
            set {
                this.managerIdField = value;
                this.RaisePropertyChanged("ManagerId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthReaderSoapChannel : LaunchDarkly.AuthReader.AuthReaderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthReaderSoapClient : System.ServiceModel.ClientBase<LaunchDarkly.AuthReader.AuthReaderSoap>, LaunchDarkly.AuthReader.AuthReaderSoap {
        
        public AuthReaderSoapClient() {
        }
        
        public AuthReaderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthReaderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthReaderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthReaderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LaunchDarkly.AuthReader.ActiveDirectoryUserInformationResponse GetActiveDirectoryUserInformation(string userId, string callerId) {
            return base.Channel.GetActiveDirectoryUserInformation(userId, callerId);
        }
        
        public System.Threading.Tasks.Task<LaunchDarkly.AuthReader.ActiveDirectoryUserInformationResponse> GetActiveDirectoryUserInformationAsync(string userId, string callerId) {
            return base.Channel.GetActiveDirectoryUserInformationAsync(userId, callerId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mytravel.se", ConfigurationName="AuthReader.AuthReaderSoap1")]
    public interface AuthReaderSoap1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/isAuthorizedXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string isAuthorizedXML(string accessProfileRequestXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/isAuthorizedXML", ReplyAction="*")]
        System.Threading.Tasks.Task<string> isAuthorizedXMLAsync(string accessProfileRequestXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/isAuthorizedXMLFromParams", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string isAuthorizedXMLFromParams(string userNo, string systemRoleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/isAuthorizedXMLFromParams", ReplyAction="*")]
        System.Threading.Tasks.Task<string> isAuthorizedXMLFromParamsAsync(string userNo, string systemRoleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/isAuthorized", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string isAuthorized(string userNo, string systemRoleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/isAuthorized", ReplyAction="*")]
        System.Threading.Tasks.Task<string> isAuthorizedAsync(string userNo, string systemRoleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getAccessProfile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string getAccessProfile(string userNo, long systemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getAccessProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getAccessProfileAsync(string userNo, long systemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getAccessProfileById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string getAccessProfileById(long accessProfileTypeId, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getAccessProfileById", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getAccessProfileByIdAsync(long accessProfileTypeId, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getAccessProfileForSystemRoleXMLFromParams", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string getAccessProfileForSystemRoleXMLFromParams(string userNo, string systemRoleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getAccessProfileForSystemRoleXMLFromParams", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getAccessProfileForSystemRoleXMLFromParamsAsync(string userNo, string systemRoleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getAccessProfileForUserRole", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string getAccessProfileForUserRole(long roleId, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getAccessProfileForUserRole", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getAccessProfileForUserRoleAsync(long roleId, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getAccessProfileValuesForUserRole", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string getAccessProfileValuesForUserRole(string userNo, long roleId, string editUserNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getAccessProfileValuesForUserRole", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getAccessProfileValuesForUserRoleAsync(string userNo, long roleId, string editUserNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/listAllAccessProfileValueTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string listAllAccessProfileValueTypes(string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/listAllAccessProfileValueTypes", ReplyAction="*")]
        System.Threading.Tasks.Task<string> listAllAccessProfileValueTypesAsync(string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/listRolesForItProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string listRolesForItProduct(long itProductId, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/listRolesForItProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<string> listRolesForItProductAsync(long itProductId, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getRolesForSystemRole", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string getRolesForSystemRole(string systemRoleName, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getRolesForSystemRole", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getRolesForSystemRoleAsync(string systemRoleName, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getRoleById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string getRoleById(long roleId, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getRoleById", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getRoleByIdAsync(long roleId, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getSystemRoleByName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string getSystemRoleByName(string systemRoleName, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getSystemRoleByName", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getSystemRoleByNameAsync(string systemRoleName, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getSystemRoleForItProductAndRole", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string getSystemRoleForItProductAndRole(string userNo, long itProductId, long roleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getSystemRoleForItProductAndRole", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getSystemRoleForItProductAndRoleAsync(string userNo, long itProductId, long roleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/listSystemRolesForITSystem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string listSystemRolesForITSystem(string userNo, long itProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/listSystemRolesForITSystem", ReplyAction="*")]
        System.Threading.Tasks.Task<string> listSystemRolesForITSystemAsync(string userNo, long itProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/listAllRolesNotAssociatedWithUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string listAllRolesNotAssociatedWithUser(string userNo, System.DateTime date, string editUserNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/listAllRolesNotAssociatedWithUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> listAllRolesNotAssociatedWithUserAsync(string userNo, System.DateTime date, string editUserNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/listRolesForUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string listRolesForUser(string userNo, System.DateTime date, string editUserNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/listRolesForUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> listRolesForUserAsync(string userNo, System.DateTime date, string editUserNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/listRolesUniqueForItProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string listRolesUniqueForItProduct(long itProductId, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/listRolesUniqueForItProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<string> listRolesUniqueForItProductAsync(long itProductId, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/listAllRoles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string listAllRoles(string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/listAllRoles", ReplyAction="*")]
        System.Threading.Tasks.Task<string> listAllRolesAsync(string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/listRolesWithProfilesForUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string listRolesWithProfilesForUser(string userNo, string editUserNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/listRolesWithProfilesForUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> listRolesWithProfilesForUserAsync(string userNo, string editUserNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/listAllITSystems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string listAllITSystems(string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/listAllITSystems", ReplyAction="*")]
        System.Threading.Tasks.Task<string> listAllITSystemsAsync(string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getItProductXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string getItProductXML(long itProductId, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getItProductXML", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getItProductXMLAsync(long itProductId, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/searchITSystem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string searchITSystem(string search, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/searchITSystem", ReplyAction="*")]
        System.Threading.Tasks.Task<string> searchITSystemAsync(string search, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getUserInformation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string getUserInformation(string editUserNo, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getUserInformation", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getUserInformationAsync(string editUserNo, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getUserInformationMUCD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string getUserInformationMUCD(string editUserNo, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getUserInformationMUCD", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getUserInformationMUCDAsync(string editUserNo, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getADUserInformationByName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string getADUserInformationByName(string editName, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/getADUserInformationByName", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getADUserInformationByNameAsync(string editName, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/searchUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        string searchUser(string search, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mytravel.se/searchUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> searchUserAsync(string search, string userNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthReaderSoap1Channel : LaunchDarkly.AuthReader.AuthReaderSoap1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthReaderSoap1Client : System.ServiceModel.ClientBase<LaunchDarkly.AuthReader.AuthReaderSoap1>, LaunchDarkly.AuthReader.AuthReaderSoap1 {
        
        public AuthReaderSoap1Client() {
        }
        
        public AuthReaderSoap1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthReaderSoap1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthReaderSoap1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthReaderSoap1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string isAuthorizedXML(string accessProfileRequestXML) {
            return base.Channel.isAuthorizedXML(accessProfileRequestXML);
        }
        
        public System.Threading.Tasks.Task<string> isAuthorizedXMLAsync(string accessProfileRequestXML) {
            return base.Channel.isAuthorizedXMLAsync(accessProfileRequestXML);
        }
        
        public string isAuthorizedXMLFromParams(string userNo, string systemRoleName) {
            return base.Channel.isAuthorizedXMLFromParams(userNo, systemRoleName);
        }
        
        public System.Threading.Tasks.Task<string> isAuthorizedXMLFromParamsAsync(string userNo, string systemRoleName) {
            return base.Channel.isAuthorizedXMLFromParamsAsync(userNo, systemRoleName);
        }
        
        public string isAuthorized(string userNo, string systemRoleName) {
            return base.Channel.isAuthorized(userNo, systemRoleName);
        }
        
        public System.Threading.Tasks.Task<string> isAuthorizedAsync(string userNo, string systemRoleName) {
            return base.Channel.isAuthorizedAsync(userNo, systemRoleName);
        }
        
        public string getAccessProfile(string userNo, long systemId) {
            return base.Channel.getAccessProfile(userNo, systemId);
        }
        
        public System.Threading.Tasks.Task<string> getAccessProfileAsync(string userNo, long systemId) {
            return base.Channel.getAccessProfileAsync(userNo, systemId);
        }
        
        public string getAccessProfileById(long accessProfileTypeId, string userNo) {
            return base.Channel.getAccessProfileById(accessProfileTypeId, userNo);
        }
        
        public System.Threading.Tasks.Task<string> getAccessProfileByIdAsync(long accessProfileTypeId, string userNo) {
            return base.Channel.getAccessProfileByIdAsync(accessProfileTypeId, userNo);
        }
        
        public string getAccessProfileForSystemRoleXMLFromParams(string userNo, string systemRoleName) {
            return base.Channel.getAccessProfileForSystemRoleXMLFromParams(userNo, systemRoleName);
        }
        
        public System.Threading.Tasks.Task<string> getAccessProfileForSystemRoleXMLFromParamsAsync(string userNo, string systemRoleName) {
            return base.Channel.getAccessProfileForSystemRoleXMLFromParamsAsync(userNo, systemRoleName);
        }
        
        public string getAccessProfileForUserRole(long roleId, string userNo) {
            return base.Channel.getAccessProfileForUserRole(roleId, userNo);
        }
        
        public System.Threading.Tasks.Task<string> getAccessProfileForUserRoleAsync(long roleId, string userNo) {
            return base.Channel.getAccessProfileForUserRoleAsync(roleId, userNo);
        }
        
        public string getAccessProfileValuesForUserRole(string userNo, long roleId, string editUserNo) {
            return base.Channel.getAccessProfileValuesForUserRole(userNo, roleId, editUserNo);
        }
        
        public System.Threading.Tasks.Task<string> getAccessProfileValuesForUserRoleAsync(string userNo, long roleId, string editUserNo) {
            return base.Channel.getAccessProfileValuesForUserRoleAsync(userNo, roleId, editUserNo);
        }
        
        public string listAllAccessProfileValueTypes(string userNo) {
            return base.Channel.listAllAccessProfileValueTypes(userNo);
        }
        
        public System.Threading.Tasks.Task<string> listAllAccessProfileValueTypesAsync(string userNo) {
            return base.Channel.listAllAccessProfileValueTypesAsync(userNo);
        }
        
        public string listRolesForItProduct(long itProductId, string userNo) {
            return base.Channel.listRolesForItProduct(itProductId, userNo);
        }
        
        public System.Threading.Tasks.Task<string> listRolesForItProductAsync(long itProductId, string userNo) {
            return base.Channel.listRolesForItProductAsync(itProductId, userNo);
        }
        
        public string getRolesForSystemRole(string systemRoleName, string userNo) {
            return base.Channel.getRolesForSystemRole(systemRoleName, userNo);
        }
        
        public System.Threading.Tasks.Task<string> getRolesForSystemRoleAsync(string systemRoleName, string userNo) {
            return base.Channel.getRolesForSystemRoleAsync(systemRoleName, userNo);
        }
        
        public string getRoleById(long roleId, string userNo) {
            return base.Channel.getRoleById(roleId, userNo);
        }
        
        public System.Threading.Tasks.Task<string> getRoleByIdAsync(long roleId, string userNo) {
            return base.Channel.getRoleByIdAsync(roleId, userNo);
        }
        
        public string getSystemRoleByName(string systemRoleName, string userNo) {
            return base.Channel.getSystemRoleByName(systemRoleName, userNo);
        }
        
        public System.Threading.Tasks.Task<string> getSystemRoleByNameAsync(string systemRoleName, string userNo) {
            return base.Channel.getSystemRoleByNameAsync(systemRoleName, userNo);
        }
        
        public string getSystemRoleForItProductAndRole(string userNo, long itProductId, long roleId) {
            return base.Channel.getSystemRoleForItProductAndRole(userNo, itProductId, roleId);
        }
        
        public System.Threading.Tasks.Task<string> getSystemRoleForItProductAndRoleAsync(string userNo, long itProductId, long roleId) {
            return base.Channel.getSystemRoleForItProductAndRoleAsync(userNo, itProductId, roleId);
        }
        
        public string listSystemRolesForITSystem(string userNo, long itProductId) {
            return base.Channel.listSystemRolesForITSystem(userNo, itProductId);
        }
        
        public System.Threading.Tasks.Task<string> listSystemRolesForITSystemAsync(string userNo, long itProductId) {
            return base.Channel.listSystemRolesForITSystemAsync(userNo, itProductId);
        }
        
        public string listAllRolesNotAssociatedWithUser(string userNo, System.DateTime date, string editUserNo) {
            return base.Channel.listAllRolesNotAssociatedWithUser(userNo, date, editUserNo);
        }
        
        public System.Threading.Tasks.Task<string> listAllRolesNotAssociatedWithUserAsync(string userNo, System.DateTime date, string editUserNo) {
            return base.Channel.listAllRolesNotAssociatedWithUserAsync(userNo, date, editUserNo);
        }
        
        public string listRolesForUser(string userNo, System.DateTime date, string editUserNo) {
            return base.Channel.listRolesForUser(userNo, date, editUserNo);
        }
        
        public System.Threading.Tasks.Task<string> listRolesForUserAsync(string userNo, System.DateTime date, string editUserNo) {
            return base.Channel.listRolesForUserAsync(userNo, date, editUserNo);
        }
        
        public string listRolesUniqueForItProduct(long itProductId, string userNo) {
            return base.Channel.listRolesUniqueForItProduct(itProductId, userNo);
        }
        
        public System.Threading.Tasks.Task<string> listRolesUniqueForItProductAsync(long itProductId, string userNo) {
            return base.Channel.listRolesUniqueForItProductAsync(itProductId, userNo);
        }
        
        public string listAllRoles(string userNo) {
            return base.Channel.listAllRoles(userNo);
        }
        
        public System.Threading.Tasks.Task<string> listAllRolesAsync(string userNo) {
            return base.Channel.listAllRolesAsync(userNo);
        }
        
        public string listRolesWithProfilesForUser(string userNo, string editUserNo) {
            return base.Channel.listRolesWithProfilesForUser(userNo, editUserNo);
        }
        
        public System.Threading.Tasks.Task<string> listRolesWithProfilesForUserAsync(string userNo, string editUserNo) {
            return base.Channel.listRolesWithProfilesForUserAsync(userNo, editUserNo);
        }
        
        public string listAllITSystems(string userNo) {
            return base.Channel.listAllITSystems(userNo);
        }
        
        public System.Threading.Tasks.Task<string> listAllITSystemsAsync(string userNo) {
            return base.Channel.listAllITSystemsAsync(userNo);
        }
        
        public string getItProductXML(long itProductId, string userNo) {
            return base.Channel.getItProductXML(itProductId, userNo);
        }
        
        public System.Threading.Tasks.Task<string> getItProductXMLAsync(long itProductId, string userNo) {
            return base.Channel.getItProductXMLAsync(itProductId, userNo);
        }
        
        public string searchITSystem(string search, string userNo) {
            return base.Channel.searchITSystem(search, userNo);
        }
        
        public System.Threading.Tasks.Task<string> searchITSystemAsync(string search, string userNo) {
            return base.Channel.searchITSystemAsync(search, userNo);
        }
        
        public string getUserInformation(string editUserNo, string userNo) {
            return base.Channel.getUserInformation(editUserNo, userNo);
        }
        
        public System.Threading.Tasks.Task<string> getUserInformationAsync(string editUserNo, string userNo) {
            return base.Channel.getUserInformationAsync(editUserNo, userNo);
        }
        
        public string getUserInformationMUCD(string editUserNo, string userNo) {
            return base.Channel.getUserInformationMUCD(editUserNo, userNo);
        }
        
        public System.Threading.Tasks.Task<string> getUserInformationMUCDAsync(string editUserNo, string userNo) {
            return base.Channel.getUserInformationMUCDAsync(editUserNo, userNo);
        }
        
        public string getADUserInformationByName(string editName, string userNo) {
            return base.Channel.getADUserInformationByName(editName, userNo);
        }
        
        public System.Threading.Tasks.Task<string> getADUserInformationByNameAsync(string editName, string userNo) {
            return base.Channel.getADUserInformationByNameAsync(editName, userNo);
        }
        
        public string searchUser(string search, string userNo) {
            return base.Channel.searchUser(search, userNo);
        }
        
        public System.Threading.Tasks.Task<string> searchUserAsync(string search, string userNo) {
            return base.Channel.searchUserAsync(search, userNo);
        }
    }
}
